on: [push]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run action
        id: hello
        uses: ./
        with:
          myInput: "overwrite default"
      - name : output
        run: |
          echo ${{ steps.hello.outputs.memory }}
          echo "done"
